(() => {
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n)), ease=n=>1-Math.pow(1-clamp(n),3);
  const scenes=['cover','boy','question','man','world'], labels=['邀请','男孩','转折','男人','今晚'], panels=$$('.panel');
  const loader=$('#loader'),enter=$('#enterButton'),bar=$('#loaderBar'),status=$('#loaderStatus'),experience=$('#experience');
  const rail=$('#progressRail'),badge=$('#chapterBadge'),hint=$('#scrollHint'),intro=$('#introAudio'),aizo=$('#aizoAudio');
  const modal=$('#mediaModal'),modalVideo=$('#modalVideo'),moduleOverlay=$('#moduleOverlay'),modulePreview=$('#modulePreview');
  let current=0,entered=false,transitioning=false,muted=false,aizoStarted=false,questionTimer=0,audioBeforeModal=null;
  let touch={x:0,y:0},pointer={x:innerWidth/2,y:innerHeight/2},lastNav=0;

  async function hydrate(el,mime){const p=el.dataset.parts?.split(',');if(!p)return;try{const rs=await Promise.all(p.map(x=>fetch(x.trim()))),bs=await Promise.all(rs.map(r=>r.blob()));el.src=URL.createObjectURL(new Blob(bs,{type:mime}));el.load()}catch(e){console.error('媒体装载失败',e)}}
  hydrate(aizo,'audio/mpeg');intro.volume=.72;aizo.volume=.78;
  function fade(audio,target,d=450,pause=false){if(!audio)return;const from=audio.volume,start=performance.now();function tick(now){const p=clamp((now-start)/d);audio.volume=from+(target-from)*ease(p);if(p<1)requestAnimationFrame(tick);else if(pause)audio.pause()}requestAnimationFrame(tick)}
  async function playIntro(reset=false){if(muted)return;if(reset)intro.currentTime=0;aizo.pause();intro.volume=.05;try{await intro.play()}catch(_){}fade(intro,.72,650)}
  async function playAizo(){if(!aizoStarted){aizoStarted=true;aizo.currentTime=0}if(muted||modal.classList.contains('is-open'))return;intro.pause();aizo.volume=.05;try{await aizo.play()}catch(_){}fade(aizo,.78,650)}
  function sceneAudio(s){if(!entered||muted)return;if(['cover','boy'].includes(s)){aizo.pause();if(intro.paused)playIntro(s==='boy')}else if(s==='question')fade(intro,0,250,true);else playAizo()}
  labels.forEach((x,i)=>{const b=document.createElement('button');b.title=x;b.setAttribute('aria-label',`前往${x}`);b.onclick=()=>goTo(i);rail.append(b)});const railButtons=$$('#progressRail button');
  function updateUI(){railButtons.forEach((b,i)=>b.classList.toggle('is-active',i===current));const s=scenes[current];badge.textContent=s==='boy'?'男孩的七夕':'男人的七夕';badge.classList.toggle('is-visible',['boy','man','world'].includes(s));hint.style.opacity=['question','world'].includes(s)?'0':'.65'}
  function goTo(i,opt={}){i=clamp(i,0,scenes.length-1);if((transitioning&&!opt.force)||i===current)return;clearTimeout(questionTimer);transitioning=true;panels[current].classList.remove('is-active');current=i;panels[current].classList.add('is-active');updateUI();sceneAudio(scenes[current]);if(scenes[current]==='boy')startBoy();if(scenes[current]==='world')enterWorld();setTimeout(()=>transitioning=false,760);if(scenes[current]==='question'){const q=$('.question-panel p');q.textContent='但今晚，还没有结束。';questionTimer=setTimeout(()=>{q.classList.add('is-switching');setTimeout(()=>{q.textContent='那，男人呢？';q.classList.remove('is-switching')},280)},1200);setTimeout(()=>goTo(3,{force:true}),3000)}}
  function move(d){if(!entered||modal.classList.contains('is-open')||moduleOverlay.classList.contains('is-open'))return;if(scenes[current]==='world')return stepWorld(d);goTo(current+d)}
  $$('[data-next]').forEach(b=>b.onclick=()=>move(1));$$('[data-go]').forEach(b=>b.onclick=()=>goTo(+b.dataset.go));

  /* hand-drawn prologue */
  const boy=$('#boyCanvas'),bc=boy.getContext('2d'),captions=$$('#boyCaption p');let boyProgress=0,branch=null,choice=false,speed=1,boyRaf=0;
  function resize(c,ctx){const d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
  function line(ctx,a,b,c,d,color='#171513',w=3){ctx.strokeStyle=color;ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()}
  function person(ctx,x,y,s,f=1,wave=0,color='#171513'){ctx.save();ctx.translate(x,y);ctx.scale(s*f,s);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3/s;ctx.beginPath();ctx.arc(0,-58,16,0,7);ctx.stroke();line(ctx,0,-42,0,24,color,3/s);line(ctx,0,-18,-28,6,color,3/s);line(ctx,0,-18,28,-2-wave*13,color,3/s);line(ctx,0,24,-20,70,color,3/s);line(ctx,0,24,23,70,color,3/s);ctx.beginPath();ctx.arc(6,-61,2.2,0,7);ctx.fill();ctx.restore()}
  function heart(ctx,x,y,s,a=1){ctx.save();ctx.globalAlpha=a;ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#a81720';ctx.beginPath();ctx.moveTo(0,7);ctx.bezierCurveTo(-24,-9,-18,-27,0,-14);ctx.bezierCurveTo(18,-27,24,-9,0,7);ctx.fill();ctx.restore()}
  function flower(ctx,x,y,s,a=1){ctx.save();ctx.globalAlpha=a;ctx.translate(x,y);line(ctx,0,0,-8,54,'#356247',2);ctx.fillStyle='#a81720';for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.ellipse(0,-s*.46,s*.22,s*.45,0,0,7);ctx.fill()}ctx.restore()}
  function bench(ctx,x,y,w){line(ctx,x-w/2,y,x+w/2,y,'#171513',5);line(ctx,x-w*.36,y,x-w*.4,y+42,'#171513',3);line(ctx,x+w*.36,y,x+w*.4,y+42,'#171513',3)}
  function drawScene(i,l,a,w,h,s){const y=h*.6,c=w*.5,k=ease(l);bc.save();bc.globalAlpha=a;if(i===0){const g=w*.16+(1-k)*w*.22;person(bc,c-g,y,s,1,k*.5);person(bc,c+g,y,s,-1);bc.setLineDash([5,8]);bc.strokeStyle='rgba(168,23,32,.5)';bc.beginPath();bc.moveTo(c-g+20,y-18);bc.quadraticCurveTo(c,y-80,c+g-20,y-18);bc.stroke();bc.setLineDash([])}else if(i===1){person(bc,c-w*.075,y,s,1,.35);person(bc,c+w*.075,y,s,-1,.35);heart(bc,c,y-145,.6,k)}else if(i===2){person(bc,c-w*.055,y,s,1,.2);person(bc,c+w*.055,y,s,-1,.2);bc.strokeStyle='#555';bc.beginPath();bc.arc(c,y-100,85*s,Math.PI,Math.PI*2);bc.stroke();line(bc,c,y-100,c,y-20,'#171513',2)}else if(i===3&&!branch){person(bc,c-w*.09,y,s,1,.2);person(bc,c+w*.09,y,s,-1);flower(bc,c,y-22,18*s,k)}else if(i>=3&&branch==='failure'){if(i===3){person(bc,c-w*.15-k*w*.08,y,s);person(bc,c+w*.15+k*w*.2,y,s,-1);flower(bc,c,y+48,15*s,.7)}else{bench(bc,c,y+45,230*s);person(bc,c,y,s*.92,1,-.3);bc.fillStyle='#527fa4';for(let j=0;j<4;j++){bc.beginPath();bc.ellipse(c+(j%2?9:-9),y-48+j*10,3,7,0,0,7);bc.fill()}if(i===5){line(bc,c-92,y-115,c-12,y-65,'#a81720',2);line(bc,c+13,y-56,c+92,y-12,'#a81720',2)}}}else if(i===4){bench(bc,c,y+45,250*s);person(bc,c-w*.045,y,s*.92,1,.1);person(bc,c+w*.045,y,s*.92,-1,.1);heart(bc,c,y-138,.7,k)}else{person(bc,c-w*.025,y,s,1,.2);person(bc,c+w*.025,y,s,-1,.2);heart(bc,c,y-142,.85,k);bc.strokeStyle='#a81720';bc.lineWidth=2;bc.beginPath();bc.moveTo(c-w*.4,y-30);bc.bezierCurveTo(c-w*.2,y-95,c-w*.08,y+25,c,y-25);bc.bezierCurveTo(c+w*.08,y-75,c+w*.24,y-5,c+w*.44,y-65);bc.stroke()}bc.restore()}
  function drawBoy(){const w=innerWidth,h=innerHeight;bc.clearRect(0,0,w,h);bc.fillStyle='#f1ece4';bc.fillRect(0,0,w,h);for(let y=42;y<h;y+=56)line(bc,0,y,w,y+9,'rgba(0,0,0,.025)',1);const s=Math.max(.82,Math.min(1.28,w/1100)),q=boyProgress*6,i=Math.min(5,Math.floor(q)),l=q-i,m=ease((l-.82)/.18);drawScene(i,l,1-m,w,h,s);if(i<5&&m)drawScene(i+1,0,m,w,h,s);bc.fillStyle='rgba(0,0,0,.38)';bc.font='11px serif';bc.fillText('A SMALL STORY ABOUT TWO PEOPLE',w*.08,h*.84);requestAnimationFrame(drawBoy)}
  function startBoy(){cancelAnimationFrame(boyRaf);boyProgress=0;branch=null;choice=false;speed=1;const sb=$('#heartSpeed');sb.querySelector('span').textContent='轻点画面，让他们更快奔向彼此';sb.querySelector('b').textContent='×1';$('#storyChoice').classList.remove('is-show');captions.forEach(c=>c.classList.remove('is-show'));playIntro(true);let last=performance.now(),lastAudio=intro.currentTime;function tick(now){let dt=Math.min(.12,(now-last)/1000);last=now;const at=intro.currentTime;if(!muted&&at>lastAudio)dt=at-lastAudio;lastAudio=at;const duration=intro.duration>1?intro.duration:176;if(!choice)boyProgress=clamp(boyProgress+dt/duration*speed);if(boyProgress>=.46&&!branch&&!choice){choice=true;boyProgress=.46;intro.pause();$('#storyChoice').classList.add('is-show')}const cues=[.06,.2,.37,.54,.7,.86];captions.forEach((c,i)=>c.classList.toggle('is-show',boyProgress>cues[i]&&boyProgress<cues[i]+.2));if(boyProgress<1&&scenes[current]==='boy')boyRaf=requestAnimationFrame(tick);else if(boyProgress>=1)goTo(2,{force:true})}boyRaf=requestAnimationFrame(tick)}
  $$('#storyChoice [data-branch]').forEach(b=>b.onclick=()=>{branch=b.dataset.branch;choice=false;$('#storyChoice').classList.remove('is-show');const copy=branch==='failure'?['遇见一个人','交换一些心事','差一点说出口','她走向了远处','花没有送出去','有些心意，只来得及经过']:['遇见一个人','交换一些心事','陪她走一段路','分享安静的时刻','送上一束花','有些心意，得到了回应'];copy.forEach((t,i)=>captions[i].textContent=t);if(!muted)intro.play().catch(()=>{})});
  $('#heartSpeed').onclick=e=>{e.stopPropagation();const ss=[1,2.2,3.5,5],i=Math.min(ss.indexOf(speed)+1,3);speed=ss[i];e.currentTarget.querySelector('span').textContent=i===3?'他们正在全力奔向彼此':'心动正在悄悄加速';e.currentTarget.querySelector('b').textContent=`×${speed}`};

  const energy=$('#energyCanvas'),ec=energy.getContext('2d'),particles=Array.from({length:65},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.7+.3,s:Math.random()*.0013+.0004}));
  function drawEnergy(){const w=innerWidth,h=innerHeight;ec.clearRect(0,0,w,h);const g=ec.createRadialGradient(w*.72,h*.46,0,w*.72,h*.46,w*.6);g.addColorStop(0,'rgba(168,23,32,.2)');g.addColorStop(1,'transparent');ec.fillStyle=g;ec.fillRect(0,0,w,h);particles.forEach(p=>{p.y-=p.s;if(p.y<0)p.y=1;ec.fillStyle='#ffffff66';ec.beginPath();ec.arc(p.x*w,p.y*h,p.r,0,7);ec.fill()});requestAnimationFrame(drawEnergy)}

  /* spatial wall */
  const world=$('.world-panel'),wc=$('#worldCanvas'),ctx=wc.getContext('2d'),nodes={game:$('.node-game'),ai:$('.node-ai'),anime:$('.node-anime')};
  const milestones={game:.20,ai:.40,anime:.60},visited=new Set(),reached=new Set();
  let worldProgress=0,worldPhase='intro',yaw=0,targetYaw=0,pull=0,overhead=0,activeModule=null,doorClicks=0,afterTimer=0,stationLock=0,revealStarted=false,collapseParticles=[];
  const route=[];
  function bezier(a,b,c,d,count=26){for(let i=route.length?1:0;i<=count;i++){const t=i/count,u=1-t;route.push([u*u*u*a[0]+3*u*u*t*b[0]+3*u*t*t*c[0]+t*t*t*d[0],u*u*u*a[1]+3*u*u*t*b[1]+3*u*t*t*c[1]+t*t*t*d[1]])}}
  bezier([-1.58,.22],[-1.48,-.18],[-1.16,-.2],[-1.02,-.06]);
  bezier([-1.02,-.06],[-.68,.05],[-.18,.62],[.22,.45]);
  bezier([.22,.45],[.58,.32],[.94,-.23],[1.28,-.08]);
  bezier([1.28,-.08],[1.62,.28],[.86,.68],[.08,.12],32);
  bezier([.08,.12],[-.5,.72],[-1.42,.62],[-1.82,.3],22);
  const nodePos={game:{x:-1.02,y:-.38},ai:{x:.22,y:.17},anime:{x:1.28,y:-.38}};
  function pointAt(p){const k=p*(route.length-1),i=Math.floor(k),f=k-i,a=route[Math.min(i,route.length-1)],b=route[Math.min(i+1,route.length-1)];return{x:a[0]+(b[0]-a[0])*f,y:a[1]+(b[1]-a[1])*f}}
  function project(p){const s=Math.min(innerWidth,innerHeight)*(.49-pull*.09),r=p.x-yaw,d=Math.cos(r*.93),side={x:innerWidth/2+Math.sin(r*1.08)*s*1.28,y:innerHeight/2+p.y*s-d*28*(1-pull),scale:clamp(.69+d*.25-pull*.08,.48,1.08),depth:d},top={x:innerWidth/2+(p.x-.04)*Math.min(innerWidth*.285,390),y:innerHeight/2+p.y*Math.min(innerHeight*.62,470),scale:.7,depth:1};return{x:side.x+(top.x-side.x)*overhead,y:side.y+(top.y-side.y)*overhead,scale:side.scale+(top.scale-side.scale)*overhead,depth:side.depth}}
  function enterWorld(){worldPhase='intro';worldProgress=0;yaw=route[0][0];targetYaw=yaw;pull=0;overhead=0;stationLock=0;revealStarted=false;reached.clear();world.className='panel world-panel is-active';Object.values(nodes).forEach(n=>n.classList.remove('is-awake','is-reached'));setTimeout(()=>{if(scenes[current]==='world'){worldPhase='tour';world.classList.add('is-touring')}},900)}
  function arrive(name){if(reached.has(name))return;reached.add(name);nodes[name].classList.add('is-awake','is-reached');stationLock=performance.now()+2000;world.classList.add('is-paused');$('#worldGuide span').textContent='已经抵达。靠近看看，或稍后继续。';setTimeout(()=>{world.classList.remove('is-paused');if(worldPhase==='tour')$('#worldGuide span').textContent='滚动，让今晚继续发生'},2000)}
  function beginReveal(){if(revealStarted)return;revealStarted=true;worldPhase='reveal';world.classList.add('is-revealing');$('#worldGuide span').textContent='原来，刚才走过的是……';setTimeout(()=>{worldPhase='descend';$('#worldGuide span').textContent='继续，陪它走到缺口。';setTimeout(()=>{worldPhase='finalwalk';world.classList.add('is-finalwalk');$('#contactDoor').classList.add('is-visible')},1500)},2400)}
  function stepWorld(d){if(activeModule||performance.now()<stationLock)return;if(worldPhase==='intro'){worldPhase='tour';world.classList.add('is-touring')}if(worldPhase==='tour'){const before=worldProgress;worldProgress=clamp(worldProgress+d*.022,0,.83);if(d<0&&worldProgress===0)return goTo(3);for(const [k,v] of Object.entries(milestones))if(before<v&&worldProgress>=v){worldProgress=v;arrive(k);break}if(worldProgress>=.83)beginReveal()}else if(worldPhase==='finalwalk'){worldProgress=clamp(worldProgress+d*.018,.83,1);if(worldProgress>=.985){worldProgress=1;worldPhase='door';$('#contactDoor').classList.add('is-ready');$('#worldFinale').classList.add('is-show');world.classList.add('is-final');$('#worldGuide').style.opacity='0'}}}
  function spawnCollapse(){collapseParticles=Array.from({length:180},(_,i)=>({x:innerWidth*(.18+Math.random()*.64),y:innerHeight*(.16+Math.random()*.68),vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*6-1,r:Math.random()*3+.7,a:1,c:i%4?'#6f1018':'#13090b'}))}
  function drawWorld(t){
    const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const pulse=(Math.sin(t/1600)+1)/2,g=ctx.createRadialGradient(w*(.4+.22*Math.sin(t/4200)),h*.42,0,w*.5,h*.5,w*.85);g.addColorStop(0,`rgb(${82+30*pulse},10,18)`);g.addColorStop(.5,'#2a080d');g.addColorStop(1,'#050405');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
    if(worldPhase==='reveal'){overhead+=(1-overhead)*.035;pull+=(1-pull)*.03;targetYaw=.04}else if(['descend','finalwalk','door'].includes(worldPhase)){overhead+=(0-overhead)*.035;pull+=(0-pull)*.035;targetYaw=pointAt(Math.max(.83,worldProgress)).x}
    for(let i=-12;i<=12;i++){const x=i/8+yaw,p=project({x,y:-.78}),q=project({x,y:.82});line(ctx,p.x,p.y,q.x,q.y,'rgba(255,255,255,.018)',1)}
    const samples=420,dormantEnd=(revealStarted?1:.83),dormantSteps=Math.floor(samples*dormantEnd);ctx.beginPath();for(let i=0;i<=dormantSteps;i++){const p=project(pointAt(i/samples));i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.strokeStyle='rgba(92,20,29,.42)';ctx.lineWidth=overhead>.25?10:4;ctx.stroke();
    const lit=Math.floor(samples*worldProgress);ctx.beginPath();for(let i=0;i<=lit;i++){const p=project(pointAt(i/samples));i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.strokeStyle='rgba(255,249,242,.82)';ctx.shadowBlur=18;ctx.shadowColor='#fff';ctx.lineWidth=overhead>.25?3:2;ctx.stroke();ctx.shadowBlur=0;
    const wp=project(pointAt(worldProgress));person(ctx,wp.x,wp.y+42*(1-overhead),Math.max(.42,wp.scale*.68),1,Math.sin(t/220)*.16,'#fff');const end=project(pointAt(1)),door=$('#contactDoor');door.style.left=`${end.x}px`;door.style.top=`${end.y-18}px`;
    if(worldPhase==='tour')targetYaw=pointAt(clamp(worldProgress+.045)).x;yaw+=(targetYaw-yaw)*.048;
    Object.entries(nodePos).forEach(([k,v])=>{const p=project(v),el=nodes[k];el.style.left=`${p.x}px`;el.style.top=`${p.y}px`;el.style.opacity=worldProgress+(.13)>=milestones[k]?String(clamp(.25+p.depth*.6,.24,1)):'0';if(!el.matches(':hover'))el.style.transform=`translate(-50%,-50%) scale(${p.scale})`});
    $('#worldProgressBar').style.width=`${worldProgress*100}%`;$('#worldProgressLabel').textContent=worldPhase==='reveal'?'俯视这段路':worldPhase==='finalwalk'?'走向那扇门':`沿着光 · ${Math.round(worldProgress*100)}%`;
    collapseParticles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vx+=(innerWidth*.5-p.x)*.0008;p.vy+=(innerHeight*.48-p.y)*.0008;p.a-=.018;ctx.globalAlpha=Math.max(0,p.a);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});ctx.globalAlpha=1;collapseParticles=collapseParticles.filter(p=>p.a>0);requestAnimationFrame(drawWorld)
  }

  const data={game:{k:'01 / ENTER ANOTHER WORLD',t:'殴打一些\n游戏。',q:'有人奔赴约会，有人奔赴另一个世界。都算赴约。',v:'assets/genshin-start.mp4',time:12.3,imgs:['game-ice.jpg','game-comic.jpg','game-red.jpg','game-soft.jpg']},ai:{k:'02 / TALK TO THE UNKNOWN',t:'训练一些\nAI。',q:'有人交换心意，有人向未知发问。好奇心，也是一种心动。',v:'assets/ai-shinjuku.mp4',imgs:['ai-kimi.png','ai-chatgpt.png','ai-whale.jpg','ai-group.jpg'],source:'https://www.bilibili.com/video/BV1pvbX6cE5s'},anime:{k:'03 / MEET AT FRAME 24',t:'欣赏一些\n作品。',q:'有些相遇发生在现实，有些相遇发生在第二十四帧。',parts:['assets/re0-op.mp4.part01','assets/re0-op.mp4.part02','assets/re0-op.mp4.part03'],imgs:['re0-1.jpg','re0-2.jpg','re0-3.jpg','re0-4.jpg','re0-5.jpg']}};
  async function parts(xs){const rs=await Promise.all(xs.map(x=>fetch(x))),bs=await Promise.all(rs.map(r=>r.blob()));return URL.createObjectURL(new Blob(bs,{type:'video/mp4'}))}
  async function openModule(k){if(!reached.has(k)||['reveal','descend','finalwalk','door'].includes(worldPhase))return;activeModule=k;visited.add(k);world.classList.add('has-module');moduleOverlay.classList.add('is-open');const d=data[k];$('#moduleKicker').textContent=d.k;$('#moduleTitle').innerHTML=d.t.replace('\n','<br>');$('#moduleQuote').textContent=d.q;$('#moduleScatter').innerHTML=d.imgs.map((x,i)=>`<img src="assets/${x}" alt="" style="--si:${i};--sx:${[-20,24,-27,23,0][i]}vw;--sy:${[-25,-23,24,23,32][i]}vh;--sr:${[-8,7,6,-7,2][i]}deg">`).join('');$('#moduleSource').classList.toggle('is-hidden',!d.source);if(d.source)$('#moduleSource').href=d.source;modulePreview.src=d.parts?await parts(d.parts):d.v;modulePreview.load();modulePreview.onloadedmetadata=()=>{modulePreview.currentTime=d.time||0;modulePreview.play().catch(()=>{})}}
  function after(text){clearTimeout(afterTimer);const e=$('#routeAfterword');e.classList.remove('is-show');e.textContent=text;requestAnimationFrame(()=>e.classList.add('is-show'));afterTimer=setTimeout(()=>e.classList.remove('is-show'),5200)}
  function closeModule(){if(!activeModule)return;const d=data[activeModule];modulePreview.pause();modulePreview.removeAttribute('src');modulePreview.load();activeModule=null;moduleOverlay.classList.remove('is-open');world.classList.remove('has-module');after(d.q)}
  Object.entries(nodes).forEach(([k,n])=>n.onclick=()=>openModule(k));$('#moduleBack').onclick=closeModule;
  $('#moduleFilm').onclick=()=>{if(activeModule)openModal(activeModule,modulePreview.src,data[activeModule].time||0)};
  function openModal(k,src,time){modulePreview.pause();audioBeforeModal=!aizo.paused?aizo:(!intro.paused?intro:null);if(audioBeforeModal)fade(audioBeforeModal,0,300,true);modalVideo.src=src;modalTitle.textContent=k==='game'?'GENSHIN IMPACT · START':k==='ai'?'牛来：新宿决战 · 非本人作品':'RE:ZERO · OPENING';modal.classList.add('is-open');modalVideo.load();modalVideo.onloadedmetadata=()=>{modalVideo.currentTime=time;if(!muted)modalVideo.play().catch(()=>{})}}
  function closeModal(){modal.classList.remove('is-open');modalVideo.pause();modalVideo.removeAttribute('src');modalVideo.load();if(audioBeforeModal&&!muted){audioBeforeModal.volume=.05;audioBeforeModal.play().catch(()=>{});fade(audioBeforeModal,audioBeforeModal===aizo?.78:.72,600)}audioBeforeModal=null;if(activeModule)modulePreview.play().catch(()=>{})}
  $('#closeModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};modalVideo.onended=closeModal;
  $('#contactDoor').onclick=()=>{if(++doorClicks===1){$('#contactDoor').classList.add('is-ajar');$('#worldFinale p').textContent='你真的想知道吗？';$('#worldFinale span').textContent='再推一次这扇门。';navigator.vibrate?.(32);return}document.body.classList.add('is-collapsing');spawnCollapse();fade(aizo,0,650,true);setTimeout(()=>$('#prankEnding').classList.add('is-show'),920)};
  $('#restartButton').onclick=()=>{document.body.classList.remove('is-collapsing');$('#prankEnding').classList.remove('is-show');visited.clear();reached.clear();doorClicks=0;collapseParticles=[];$('#contactDoor').classList.remove('is-ready','is-visible','is-ajar');$('#worldFinale').classList.remove('is-show');$('#worldFinale p').textContent='七夕没有标准答案。';$('#worldFinale span').textContent='你愿意把今晚交给谁、交给什么，都算赴约。';Object.values(nodes).forEach(n=>n.classList.remove('is-awake','is-reached'));aizo.pause();aizoStarted=false;goTo(0,{force:true});playIntro(true)};

  addEventListener('wheel',e=>{if(!entered||modal.classList.contains('is-open')||activeModule)return;if(scenes[current]==='world'){e.preventDefault();if(worldPhase==='explore'&&Math.abs(e.deltaX)>Math.abs(e.deltaY))targetYaw=clamp(targetYaw+e.deltaX*.0016,-1,1);else if(worldPhase!=='explore')stepWorld(e.deltaY>0?1:-1);return}if(Math.abs(e.deltaY)>18&&performance.now()-lastNav>850){lastNav=performance.now();move(e.deltaY>0?1:-1)}},{passive:false});
  addEventListener('pointermove',e=>{pointer={x:e.clientX,y:e.clientY};if(scenes[current]==='world'&&worldPhase==='explore'&&!activeModule)targetYaw=clamp((e.clientX/innerWidth-.5)*2.1,-1,1)});
  addEventListener('touchstart',e=>touch={x:e.touches[0].clientX,y:e.touches[0].clientY},{passive:true});addEventListener('touchmove',e=>{if(scenes[current]==='world'&&worldPhase==='explore'&&!activeModule){const dx=e.touches[0].clientX-touch.x;targetYaw=clamp(targetYaw-dx/innerWidth*1.7,-1,1);touch.x=e.touches[0].clientX}},{passive:true});addEventListener('touchend',e=>{const dy=touch.y-e.changedTouches[0].clientY;if(Math.abs(dy)>35){if(scenes[current]==='world'&&worldPhase!=='explore')stepWorld(dy>0?1:-1);else if(scenes[current]!=='world')move(dy>0?1:-1)}touch={x:0,y:0}},{passive:true});
  addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal.classList.contains('is-open'))closeModal();else if(activeModule)closeModule();return}if(['ArrowDown','PageDown',' ','Enter'].includes(e.key)){e.preventDefault();move(1)}if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();move(-1)}});
  $('#soundButton').onclick=()=>{muted=!muted;$('#soundButton').classList.toggle('is-muted',muted);$('#soundLabel').textContent=muted?'SOUND OFF':'SOUND ON';if(muted){intro.pause();aizo.pause()}else sceneAudio(scenes[current])};
  const cursor=$('#cursor');let cx=pointer.x,cy=pointer.y;addEventListener('pointerover',e=>cursor.classList.toggle('is-over',!!e.target.closest('button,a')));(function loop(){cx+=(pointer.x-cx)*.17;cy+=(pointer.y-cy)*.17;cursor.style.left=`${cx}px`;cursor.style.top=`${cy}px`;requestAnimationFrame(loop)})();
  $$('.qixi-word').forEach(word=>{word.addEventListener('pointermove',e=>{const r=word.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;word.style.setProperty('--qx',`${x*24}px`);word.style.setProperty('--qy',`${y*18}px`);word.style.setProperty('--qr',`${x*5}deg`)});word.addEventListener('pointerleave',()=>{word.style.setProperty('--qx','0px');word.style.setProperty('--qy','0px');word.style.setProperty('--qr','0deg')})});
  $$('.man-copy h2,.module-copy h2,.world-finale p').forEach(title=>{title.classList.add('kinetic-title');title.addEventListener('pointermove',e=>{const r=title.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;title.style.setProperty('--title-x',`${x*14}px`);title.style.setProperty('--title-y',`${y*10}px`);title.style.setProperty('--title-ry',`${x*5}deg`);title.style.setProperty('--title-rx',`${-y*4}deg`)});title.addEventListener('pointerleave',()=>['--title-x','--title-y','--title-ry','--title-rx'].forEach(v=>title.style.removeProperty(v)))})
  resize(boy,bc);resize(energy,ec);resize(wc,ctx);addEventListener('resize',()=>{resize(boy,bc);resize(energy,ec);resize(wc,ctx)});requestAnimationFrame(drawBoy);requestAnimationFrame(drawEnergy);requestAnimationFrame(drawWorld);
  const imgs=$$('img'),media=[intro,aizo];let loaded=0,total=imgs.length+media.length,ready=false;function mark(){loaded++;const p=Math.min(100,Math.round(loaded/total*100));bar.style.width=`${p}%`;status.textContent=`正在整理今晚的可能性 · ${p}%`;if(loaded>=total)finish()}function finish(){if(ready)return;ready=true;bar.style.width='100%';status.textContent='今晚已经准备好';enter.disabled=false}imgs.forEach(im=>im.complete?mark():(im.onload=im.onerror=mark));media.forEach(m=>m.readyState>=1?mark():(m.onloadedmetadata=m.onerror=mark));setTimeout(finish,8500);
  enter.onclick=async()=>{entered=true;loader.classList.add('is-gone');experience.classList.add('is-ready');experience.setAttribute('aria-hidden','false');await playIntro(true);updateUI()};updateUI();
})();
